# Settings die matchen met de Docker-Compose file
spring.datasource.url=jdbc:postgresql://localhost:15432/hu-s3-project
spring.datasource.username=hu-s3-project-dbadmin
spring.datasource.password=hu-s3-project-pwd

# Gebruik een schema.sql om de database te initialiseren
spring.sql.init.mode=always