spring.profiles.active=s2

# We expect database called "hu-s3-project",
# with the same username and password
#spring.datasource.url=jdbc:postgresql://localhost:15432/hu-s3-project
#spring.datasource.username=hu-s3-project-dbadmin
#spring.datasource.password=hu-s3-project-pwd

# Settings voor H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
